# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kservice': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
